# Generated by Django 2.0.3 on 2018-03-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductSKU', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductPrice', models.FloatField()),
                ('ProductWeight', models.FloatField()),
                ('ProductCartDesc', models.CharField(max_length=250)),
                ('ProductShortDesc', models.CharField(max_length=1000)),
                ('ProductLongDesc', models.TextField()),
                ('ProductThumb', models.CharField(max_length=100)),
                ('ProductImage', models.CharField(max_length=100)),
                ('ProductCategoryID', models.IntegerField()),
                ('ProductUpdateDate', models.DateTimeField()),
                ('ProductStock', models.FloatField()),
                ('ProductLive', models.IntegerField()),
                ('ProductUnlimited', models.IntegerField()),
                ('ProductLocation', models.CharField(max_length=250)),
            ],
        ),
    ]
